### ISSUE TITLE
Create pages to separate the portal

### ISSUE THREAD

**Issue by IanaSanduta** [Ensign-College/survival-admin-portal#31]
Create a landing page (Create a nice landing welcoming page) 
Add the existing page we have to the separate one

**Comment by IanaSanduta** [comment]
Create a landing page
Add the existing page we have to the separate one

**Comment by zenay910** [comment]
Created a landing page with links to all the other pages. Then changed the index.tsx file to open the landing_page.tsx instead of HomePage.tsx
